version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
      - 5672:5672

  filter_rating_server_duration:
    container_name: filter_rating_server_duration
    image: filter_rating_server_duration:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - MATCH_QUEUE=match_queue
      - OUTPUT_QUEUE=output_queue_1
      - AVG_RATING_FIELD=average_rating
      - SERVER_FIELD=server
      - DURATION_FIELD=duration
      - ID_FIELD=token
    
  group_by_match:
    container_name: group_by_match
    image: group_by_match:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - PLAYER_QUEUE=player_queue
      - N_REDUCERS=2
      - GROUP_BY_MATCH_QUEUE=group_by_match_queue
      - MATCH_FIELD=match

  reducer_group_by_match_1:
    container_name: reducer_group_by_match_1
    image: reducer_group_by_match:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - GROUP_BY_MATCH_QUEUE=group_by_match_queue_1
      - MATCH_FIELD=match
      - GROUPED_PLAYERS_QUEUE=grouped_players_queue

  reducer_group_by_match_2:
    container_name: reducer_group_by_match_2
    image: reducer_group_by_match:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - GROUP_BY_MATCH_QUEUE=group_by_match_queue_2
      - MATCH_FIELD=match
      - GROUPED_PLAYERS_QUEUE=grouped_players_queue

  filter_solo_winner_player:
    container_name: filter_solo_winner_player
    image: filter_solo_winner_player:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - GROUPED_PLAYERS_QUEUE=grouped_players_queue
      - OUTPUT_QUEUE=output_queue_2
      - RATING_FIELD=rating
      - WINNER_FIELD=winner
